### ISSUE TITLE
Please tag new versions of the components 

### ISSUE THREAD

**Issue by brianpeiris** [ngokevin/aframe-event-set-component#1]
I'd like to be able to use fixed rawgit URLs that point at stable releases instead of at `master`

**Comment by ngokevin** [comment]
What about via npm? ```https://unpkg.com/aframe-event-set-component@x.x.x/dist/aframe-event-set-component.min.js```

**Comment by brianpeiris** [comment]
Ah, I didn't realize you were versioning correctly in npm but not on github. I'll use unpkg instead of rawgit. You might want to mention that in your readme. Thanks.
